# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CampusAccesible' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'GoogleMaps', '3.10.0'
  pod 'GooglePlaces', '3.10.0'

  target 'CampusAccesibleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CampusAccesibleUITests' do
    # Pods for testing
  end

end
